version: '3.5'
services:
  neo4j:
    container_name: neo4j
    image: neo4j
    ports: 
      - 7474:7474
      - 7687:7687
    restart: always
    environment: 
      - NEO4J_AUTH=none
      # NEO4J_AUTH=neo4j/password